### ISSUE TITLE
コマンドを実行してもデータパックが動かない

### ISSUE THREAD

**Issue by KoonRiol** [ChenCMD/MCCMD-ScoreDamage#4]
実行したコマンド↓
/data modify storage score_damage: Argument set value {Damage:10.00,DamageType:"Fall",BypassResistance:true}
/execute as @e[distance=..5] run function score_damage:api/attack
/data remove storage score_damage: Argument

データパック=>ちゃんと読み込まれている
実行=>エラーは出ない、114個のコマンドが実行されたと出ている
結果=>Healthに変化がない

**Comment by ChenCMD** [comment]
Minecraft及びScoreDamageのバージョン、その他にDatapackを入れていない状態でも発生するかどうか、改変の有無等を教えてください。

**Comment by KoonRiol** [comment]
Minecraft ver1.19
ScoreDamage ver3.2-1.19
データパックはScoreDamageのみ改変はしてないです

**Comment by KoonRiol** [comment]
毎日起きたらコマンド実行してみてるんですけどHealthに変化がないです・・・
そういえばoptifine入れてたので抜いてやってみます

**Comment by KoonRiol** [comment]
optifine外しても変わらなかったです

**Comment by ChenCMD** [comment]
Release修正しました
